[package]
name = "uefi_rust_allocation_lib"
version = "0.1.0"
authors = ["Jiewen Yao <jiewen.yao@intel.com>",
           "Bret Barkelew <bret.barkelew@microsoft.com"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "uefi_rust_allocation_lib"
