[package]
name = "uefi_rust_panic_lib"
version = "0.1.0"
authors = ["Jiewen Yao <jiewen.yao@intel.com>",
           "Bret Barkelew <bret.barkelew@microsoft.com"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "uefi_rust_panic_lib"
crate-type = ["rlib", "staticlib"]

# the profile used for `cargo build`
[profile.dev]
panic = "abort" # disable stack unwinding on panic

# the profile used for `cargo build --release`
[profile.release]
panic = "abort" # disable stack unwinding on panic

[dependencies]
r-efi="*"
#uefi_rust_allocation_lib = { git = "https://github.com/microsoft/mu_basecore.git", branch = "personal/brbarkel/rust_explosion" }
uefi_rust_allocation_lib = { path = "../../../MdeModulePkg/Library/UefiRustAllocationLib" }
#uefi_rust_print_lib_debug_lib = { git = "https://github.com/microsoft/mu_basecore.git", branch = "personal/brbarkel/rust_explosion" }
uefi_rust_print_lib_debug_lib = { path = "../../../MdeModulePkg/Library/UefiRustPrintLibDebugLib" }
