[package]
name = "uefi_rust_print_lib_debug_lib"
version = "0.1.0"
authors = ["Bret Barkelew <bret.barkelew@microsoft.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "uefi_rust_print_lib_debug_lib"

[dependencies]
r-efi = "2.1.0"
